service:
  name: test

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 3030

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10

functions:
  users_index:
    handler: src/controllers/users/users_controller.index
    events: ${file(./src/controllers/users/users_events.yml):index}
  users_show:
    handler: src/controllers/users/users_controller.show
    events: ${file(./src/controllers/users/users_events.yml):show}
      
